//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Headerorder
    {
        public string OrderID { get; set; }
        public string EmployeeID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Payment { get; set; }
        public string bank { get; set; }
    
        public virtual Msemployee Msemployee { get; set; }
        public virtual Msmember Msmember { get; set; }
    }
}
