//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaRestaurant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsemkaRestaurantEntities : DbContext
    {
        public EsemkaRestaurantEntities()
            : base("name=EsemkaRestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detailorder> Detailorders { get; set; }
        public virtual DbSet<Headerorder> Headerorders { get; set; }
        public virtual DbSet<Msemployee> Msemployees { get; set; }
        public virtual DbSet<Msmember> Msmembers { get; set; }
        public virtual DbSet<Msmenu> Msmenus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
